# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('min_temperature', models.IntegerField()),
                ('max_temperature', models.IntegerField()),
                ('min_days_cultivation', models.IntegerField()),
                ('max_days_cultivation', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Atualizado em')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horta.Difficulty')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='weather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horta.Weather'),
        ),
    ]
