# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 00:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Atualizado em')),
                ('condition', models.ManyToManyField(related_name='plant_condition', to='horta.Condition')),
                ('days', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='plant_days', to='horta.ConditionInterval')),
                ('ph', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='plant_ph', to='horta.ConditionInterval')),
                ('temperature', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='plant_temp', to='horta.ConditionInterval')),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='condition_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horta.ConditionType'),
        ),
    ]
