# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditioninterval',
            name='condition_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='horta.ConditionType'),
            preserve_default=False,
        ),
    ]
