# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horta', '0002_conditioninterval_condition_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Growing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='growing',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horta.Plant'),
        ),
    ]
