# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 01:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horta', '0003_auto_20160218_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowingStages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('days', models.IntegerField(default=0)),
                ('step', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Atualizado em')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horta.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Atualizado em')),
            ],
        ),
        migrations.RemoveField(
            model_name='growing',
            name='plant',
        ),
        migrations.AddField(
            model_name='growing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='growing',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='growing',
            name='stage',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='horta.GrowingStages'),
        ),
        migrations.AddField(
            model_name='growing',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='horta.User'),
        ),
    ]
