# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horta', '0004_auto_20160218_0154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrowingStages',
            new_name='GrowingStage',
        ),
    ]
